services:
  imanabboud:
    build: .
    container_name: imanabboud
    env_file:
      - .env
    ports:
      - "127.0.0.1:3001:3000"
    restart: unless-stopped
    networks:
      - projectone_default

networks:
  projectone_default:
    external: true

